auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path('watchlist/', views.watchlist, name="watchlist"),
    path('categories/',views.categories, name="categories"),
    path('categories/<str:category_name>/', views.activelist, name="activelist"),
    path('<int:list_id>/', views.detail, name="detail")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import ModelForm





class Listing(models.Model):
     title=models.CharField(max_length=64)
     description=models.TextField(max_length=500)
     starting_bid=models.DecimalField(max_digits=10, decimal_places=2)
     image_url = models.URLField(max_length=200, blank=True, null=True)
     category=models.CharField(max_length=64)
     owner=models.ForeignKey("User", on_delete=models.CASCADE, related_name="listings")
     active=models.BooleanField(default=True)
     winner=models.ForeignKey("User", on_delete=models.CASCADE, null=True, blank=True, related_name="winner")


     def __str__(self):
            return f"{self.title} "
        
        
        
        
        
class User(AbstractUser):
    watchlist=models.ManyToManyField(Listing, blank=True, related_name="watch")
    pass
        
        
        
        
        
        
        
class Bid (models.Model):
    amount=models.DecimalField(max_digits=10, decimal_places=2)
    timestamp=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_bid')
    listing=models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="listbid")
    
    
    def __str__(self):
         return f"{self.user} : {self.amount}$ "
     
     
     
     
     
     
class Comment (models.Model):
        user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
        comment=models.CharField(max_length=500)
        timestamp=models.DateTimeField(auto_now_add=True)
        listing=models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comment_listing")

        def __str__(self):
              format="%Y.%m.%d"
              return f" {self.timestamp.strftime(format)}. {self.user} :'{self.comment}' "
          
          

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect 
from django.urls import reverse
from django.forms import ModelForm
from django import forms
from .models import User ,Listing, Comment, Bid
from django.db.models import Max
from django.contrib import messages
from django.shortcuts import render, redirect


class ListingForm(ModelForm):
    class Meta:
        model = Listing
        fields = ["title", "description", "starting_bid", "image_url", "category"]
        
class BidForm(ModelForm):
    class Meta:
        model=Bid
        fields=['amount']
        
class CommentForm(ModelForm):
    class Meta:
        model=Comment
        fields=["comment"]
    

def create(request):
    if request.method == "POST":
        form=ListingForm(request.POST)
        if form.is_valid():
           listing=form.save(commit=False)
           listing.owner=request.user
           listing.save()

        return HttpResponseRedirect(reverse("index"))
    else:
            form = ListingForm()         
    listings=Listing.objects.all()    
    return render(request, "auctions/create.html",{
            "form":form,
            "listings":listings
                })
    
   
def watchlist (request):
    list=request.user.watchlist.all()

    
    if request.method=="POST":
        listid=request.POST.get("listing_id")
        listing=Listing.objects.get(id=listid)
        if listing in request.user.watchlist.all():
            request.user.watchlist.remove(listing)
        else:
            request.user.watchlist.add(listing)
            
        return redirect("watchlist")

    return render(request, "auctions/watchlist.html", {
        "list":list
    })
       
category=[]  
def categories(request):
    active_listings = Listing.objects.filter(active=True)
    listing=active_listings.values_list("category", flat=True)
    for list in listing:
        if list in category:
            continue
        else:
            category.append(list)
    
    return render(request, "auctions/categories.html",{
        'listing':category
    })
   
    
def detail(request, list_id):
    listing=Listing.objects.get(id=list_id)
    startingbid=listing.starting_bid
    bids=listing.listbid.all() 
    comment=listing.comment_listing.all()
    max_price = bids.aggregate(Max("amount"))['amount__max']
    higest_bid=bids.filter(amount=max_price).first()

    form=BidForm()
    formComment=CommentForm()
    
    if request.method=="POST":
        if "close" in request.POST and listing.owner==request.user:
         
            listing.active=False
            if higest_bid:
                listing.winner=higest_bid.user
            

            listing.save()
            return redirect('detail',list_id=listing.id)            
        
        if "submit_bid" in request.POST:
            
            form=BidForm(request.POST)
        
            if form.is_valid():
                new_bid=form.cleaned_data["amount"]
                if max_price==None:
                    max_price=startingbid
            
                if new_bid>max_price:
                        bid= form.save(commit=False)   
                        bid.user=request.user
                        bid.listing=listing
                        bid.save()
                        return redirect('detail',list_id=listing.id)
               

        elif "submit_comment" in request.POST:
            formComment=CommentForm(request.POST)
            if formComment.is_valid():

                usecomment=formComment.save(commit=False)
                usecomment.user=request.user
                usecomment.listing=listing
                usecomment.save()
                return redirect('detail',list_id=listing.id)        
       
    return render (request, "auctions/detail.html", {
        "listing":listing,
        "bids":bids,
        "form":form,
        "prize":max_price,
        "formComment":formComment,
        "comment":comment   
    })
  
def activelist(request, category_name):
    listings = Listing.objects.filter(category=category_name, active=True)

    
    return render(request, "auctions/activelist.html", {
        "listings":listings
    })
   


def index(request):
    listings = Listing.objects.filter(active=True)
    return render(request, "auctions/index.html", {"listings": listings})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")
    
    
    

auctions/templates/auctions/activelist.html
{% extends "auctions/layout.html" %}
{% block body %}


<h1>Active Listings by Category ✅</h1>

    {% for list in listings %}
    <ul>
        <li>  <a href="{% url 'detail' list.id %}">  {{ list.title }}</a> </li>
    </ul>
    {% endfor %}


{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}
{% block body %}


<h1>Categories</h1>
{% for list in listing %}
<ul>
  <li>
     <a  href= "{% url 'activelist' list %}"> {{list}} </a>
  </li>
</ul>
{% endfor %}

{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}
{% load widget_tweaks %}

{% block body %}
<h1>New Auction Item</h1>
<form action="{% url 'create' %}" method="POST" class="create-watchlist">

    {% csrf_token %}

   <div>
      <label for="floatingInput">Title:</label>
      {{ form.title |add_class:"form-control w-50" }}
   </div>
  
   <div>
      <label>Description:</label>
      {{ form.description |add_class:"form-control w-50" }}
   </div>
   
   <div>
      <label>Image url:</label>
      {{ form.image_url |add_class:"form-control w-50" }}
   </div>
   
   <div>
      <label>Starting bid:</label>
      {{ form.starting_bid |add_class:"form-control w-50" }}
   </div>
      
   <div>
      <label>Category:</label>
      {{ form.category |add_class:"form-control w-50" }}
   </div>

   <div class="create-button">
      <input type='submit' class="btn btn-primary"/>
   </div>
         
</form>

{% endblock %}

auctions/templates/auctions/detail.html
{% extends "auctions/layout.html" %}
{% load widget_tweaks %}
{% block body %}


 <!-- Auction status & owner/winner actions -->

<div class="details-close">
        <h2>Listing Details ✅</h2>

        <div class=" alert-success d-flex align-items-center">

            {% if listing.owner == user and listing.active %}
                <form action="" method='POST'>
                    {% csrf_token %}
                    <input  type="submit" name='close'  value="Close auction" class="btn btn-primary"/>
                </form>
            {% endif %}


           
            {% if listing.owner == user and not listing.active %}
              <p>This auction is closed. You were the owner.</p>
            {% elif listing.winner == user and not listing.active %}
              <h2> 🎉 You won this auction!</h2>
            {% elif listing.winner != user and not listing.active %}
              <p>This auction is closed. You didn’t win.</p>
            {% endif %}


        </div>

</div>


<div class="detail-listing">


    <!-- Listing details with watchlist button -->
    
    <div class="card list" style="width: 18rem;">
        <form action="{% url 'watchlist'  %}" method="POST" >
            {% csrf_token %}
                {% if listing.image_url %}
                    <img src="{{ listing.image_url }}" alt="{{ listing.title }}" style="width: 200px; height: 200px; object-fit: cover;"  class="card-img-top">
                 {% endif %}

                <div class="card-body">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Title:  {{listing.title}}</li>
                        <li class="list-group-item">Description :{{listing.description}}</li>
                        <li class="list-group-item">Starting_bid :  {{ listing.starting_bid }} $</li>
                    </ul>
                    <input type="hidden" name='listing_id'  value="{{ listing.id }}"/>
                    <div class="card-body">
                        {% if listing in request.user.watchlist.all%}
                            <input type="submit" name='Remove from watchlist'  value="Remove from watchlist" class="btn btn-primary"/>
                        {% else %}

                        <input type="submit" name='Add to watchlist'  value="Add to watchlist" class="btn btn-primary"/>

                        {% endif %}
                    </div>
               </div>
        </form>
    </div>



    <div class="bid-container">


        <!-- Bid warning message -->

        <div class="message-container"> 
            <p  class=" message alert alert-info" role="alert">
                Your bid must be higher than the current highest bid, or the starting bid if no bids have been made.
            </p>     
        </div>


        <!-- Bidding form, list of bids, and current highest bid -->

        <div>

            {% if listing.active and  user.is_authenticated %}
             <form action="" method="POST"  >
                {% csrf_token %}        
                <div class="amount">
                    <h2 for="floatingInput">Place Your Bid ✅</h2>
                    {{ form.amount |add_class:"form-control " }}
                </div>

                <input type="submit" name="submit_bid" class="btn btn-primary" />
             </form>
            {% endif %}

            {% for bid in bids %}
                <ol class="list-group list-group-numbered bids">
                     <li class="list-group-item">{{bid}} </li>
                </ol>   
            {% endfor %}
             <h2 class="form-control bids" >Current Highest Bid: {{prize}} $</h2>
             
         </div>


    </div>


   <!-- Comment form and user comments -->

    <div class="comment-container ">

        {% if listing.active and  user.is_authenticated %}

            <form action="" method="POST">
                {% csrf_token %}              
                <div class="comment">
                    <h2 >Comments ✅:</h2>
                    <label for="id_comment" class="form-label">Add a comment:</label>

                    {{ formComment.comment |add_class:"form-control " }}
                </div>
                <input type="submit" name="submit_comment"  class="btn btn-primary" />
            </form>

        {% endif %}


        <div class="user-comment comments mt-4 " >
              {% for com in comment %}
                <div class="comment border rounded p-2 mb-2 bg-light">
                     <div class="small text-muted">
                         {{ com.timestamp|date:"Y.m.d" }} — {{ com.user }} :
                     </div>
                     <div>"{{ com.comment }}"</div>
                </div>
               {% empty %}
                    <p>No comments yet. Be the first to comment!</p>
               {% endfor %}
        </div>

    </div>

   
</div>

  
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <div class="listing-container" style="display:flex; flex-wrap:wrap; gap:50px;">
        {% for listing in listings %}
        
            <div  class="card" style="width: 18rem; ">

                {% if listing.image_url %}
                    <img src="{{ listing.image_url }}" alt="{{ listing.title }}" style="width: 100%; height: 200px; object-fit: contain; background:#f8f9fa;" class="card-img-top">
                {% endif %}

                    <div class="card-body">
                        <ul  class="list-group list-group-flush">
                            <li class="list-group-item">Title :  {{listing.title}}</li>
                            <li class="list-group-item">Description : {{listing.description}}</li>
                            <li class="list-group-item">Starting_bid :  {{ listing.starting_bid }} $</li>
                        </ul>
                    </div>

                    <div class="card-body">
                        <a href="{% url 'detail' listing.id %}" class="card-link">See Details</a>
                    </div>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}




 

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}?v=2" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li  class="nav-item">
                <a class="nav-link" href="{% url 'create' %}">Create Listings</a>
             </li>
             <li  class="nav-item">
                <a class="nav-link" href= "{% url 'watchlist' %}"> WatchList </a>
             </li>
             <li  class="nav-item">
                 <a class="nav-link" href= "{% url 'categories' %}"> Categories </a>

            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
<h1>My Watchlist ✅</h1>

<ul>
  {% for item in list %}
    <li>
      <a href="{% url 'detail' item.id %}">{{ item.title }}</a> - {{ item.starting_bid }}$
    </li>
  {% empty %}
    <li>No items in your watchlist.</li>
  {% endfor %}
</ul>

<form action="{% url 'watchlist' %}" method="POST">
  {% csrf_token %}
  <input type="hidden" name="listing_id" value="{{ item.id }}"/>

  {% if item in request.user.watchlist.all %}
      <input type="submit" name="remove" value="Remove from watchlist"/>
  {% endif %}
</form>

{% endblock %}